
package com.paypal.cfx.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-01T15:56:41.166+05:30
 * Generated source version: 2.7.3
 */

@WebFault(name = "FaultMessage", targetNamespace = "http://svcs.paypal.com/types/common")
public class PPFaultMessage extends Exception {
    
    private com.paypal.cfx.client.FaultMessage faultMessage;

    public PPFaultMessage() {
        super();
    }
    
    public PPFaultMessage(String message) {
        super(message);
    }
    
    public PPFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public PPFaultMessage(String message, com.paypal.cfx.client.FaultMessage faultMessage) {
        super(message);
        this.faultMessage = faultMessage;
    }

    public PPFaultMessage(String message, com.paypal.cfx.client.FaultMessage faultMessage, Throwable cause) {
        super(message, cause);
        this.faultMessage = faultMessage;
    }

    public com.paypal.cfx.client.FaultMessage getFaultInfo() {
        return this.faultMessage;
    }
}
