package com.mgi.complaintproxyservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-26T15:16:15.776+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1", name = "ComplaintProxyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ComplaintProxyServicePortType {

    @WebResult(name = "insertRecsIntoCRMExtWebFormResponse", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1", partName = "parameters")
    @WebMethod(operationName = "InsertRecsIntoCRMExtWebForm", action = "http://moneygram.com/ComplaintProxyService_v1/InsertRecsIntoCRMExtWebForm")
    public InsertRecsIntoCRMExtWebFormResponse insertRecsIntoCRMExtWebForm(
        @WebParam(partName = "parameters", name = "insertRecsIntoCRMExtWebFormRequest", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1")
        InsertRecsIntoCRMExtWebFormRequest parameters
    );

    @WebResult(name = "insertRecsIntoCRMIntWebFormResponse", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1", partName = "parameters")
    @WebMethod(operationName = "InsertRecsIntoCRMIntWebForm", action = "http://moneygram.com/ComplaintProxyService_v1/InsertRecsIntoCRMIntWebForm")
    public InsertRecsIntoCRMIntWebFormResponse insertRecsIntoCRMIntWebForm(
        @WebParam(partName = "parameters", name = "insertRecsIntoCRMIntWebFormRequest", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1")
        InsertRecsIntoCRMIntWebFormRequest parameters
    );

    @WebResult(name = "insertRecToCRMResponse", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1", partName = "parameters")
    @WebMethod(operationName = "InsertRecToCRM", action = "http://moneygram.com/ComplaintProxyService_v1/InsertRecToCRM")
    public InsertRecToCRMResponse insertRecToCRM(
        @WebParam(partName = "parameters", name = "insertRecToCRMRequest", targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1")
        InsertRecToCRMRequest parameters
    );
}
