package com.mgi.complaintproxyservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.commons.configuration.PropertiesConfiguration;
import org.apache.log4j.Logger;

import com.mgi.paypal.util.PropertyUtil;

/**
 * This class was generated by Apache CXF 2.7.3 2013-03-26T15:16:15.199+05:30
 * Generated source version: 2.7.3
 * 
 */
public final class ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client {
	private static Logger LOGGER = Logger
			.getLogger(ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client.class);
	PropertiesConfiguration constantFromProperties = new PropertyUtil()
	.getConstantPropertyConfig();
	private static final QName SERVICE_NAME = new QName(
			"http://moneygram.com/service/ComplaintProxyService_v1",
			"ComplaintProxyService_v1");

	public ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client() {
	}

	private  ComplaintProxyServicePortType getPort()
			throws MalformedURLException {

		LOGGER.debug("Enter getPort.");

		// URL wsdlURL = new URL(
		// "http://extwsintsvcs.corp.moneygram.com//ComplaintProxyService//Complaint"
		// + "ProxyService_v1//META-INF//wsdl//ComplaintProxyService_v1.wsdl");

		// URL wsdlURL = new URL(
		// "http://extwsintsvcs.corp.moneygram.com/ComplaintProxyService/ComplaintPr"
		// +
		// "oxyService_v1/META-INF/wsdl/ComplaintProxyService_v1.wsdl");
		setCredentials();
//		URL wsdlURL = new URL(
//				"https://q2mgiapps.qa.moneygram.com/ComplaintProxyService/Complaint"
//						+ "ProxyService_v1/META-INF/wsdl/ComplaintProxyService_v1.wsdl");
		
		URL wsdlURL = new URL(constantFromProperties.getString("COMPLAINT_PROXY_PORT_URL"));
//				"http://extwsintsvcs.corp.moneygram.com/ComplaintPr" +
//				"oxyService/ComplaintProxyService_v1/META-INF/wsdl/ComplaintProxyService_v1.wsdl");


		ComplaintProxyServiceV1 ss = new ComplaintProxyServiceV1(wsdlURL,
				SERVICE_NAME);
		ComplaintProxyServicePortType port = ss.getComplaintProxyServiceSoap();
		
		LOGGER.debug("Exit getPort.");
		
		return port;
	}

	private static void setCredentials() {
//		 Security.setProperty("ssl.SocketFactory.provider",
//		 "com.ibm.jsse2.SSLSocketFactoryImpl");
//		 Security.setProperty("ssl.ServerSocketFactory.provider",
//		 "com.ibm.jsse2.SSLServerSocketFactoryImpl");
//		 System.setProperty("javax.net.ssl.trustStore",
//		 "CXFRest/WebContent/WEB-INF/truststore.jks");
//		 System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
	}

	public  com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormResponse insertRecsIntoCRMExtWebForm(
			com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormRequest _insertRecsIntoCRMExtWebForm_parameters)
			throws MalformedURLException {
		ComplaintProxyServicePortType port = getPort();
		com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormResponse _insertRecsIntoCRMExtWebForm__return = port
				.insertRecsIntoCRMExtWebForm(_insertRecsIntoCRMExtWebForm_parameters);
		return _insertRecsIntoCRMExtWebForm__return;
	}


}
