package com.mgi.complaintproxyservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import org.apache.log4j.Logger;

import com.mgi.paypal.util.PropertyUtil;

/**
 * This class was generated by Apache CXF 2.7.3 2013-03-26T15:16:15.199+05:30
 * Generated source version: 2.7.3
 * 
 */
public final class ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client {
	private static Logger LOGGER = Logger
			.getLogger(ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client.class);
	private static final QName SERVICE_NAME = new QName(
			"http://moneygram.com/service/ComplaintProxyService_v1",
			"ComplaintProxyService_v1");

	public ComplaintProxyServicePortType_ComplaintProxyServiceSoap_Client() {
	}

	private ComplaintProxyServicePortType getPort()
			throws MalformedURLException {

		LOGGER.debug("Enter getPort.");

		LOGGER.debug("PROXY URL from property file : "
				+ PropertyUtil.constantFromProperties
						.getString("COMPLAINT_PROXY_PORT_URL"));

		LOGGER.debug("End point URL from property file : "
				+ PropertyUtil.constantFromProperties
						.getString("COMPLAINT_PROXY_SERVICE_ENDPOINT_URL"));

		URL wsdlURL = new URL(PropertyUtil.constantFromProperties
				.getString("COMPLAINT_PROXY_PORT_URL"));

		ComplaintProxyServiceV1 ss = new ComplaintProxyServiceV1(wsdlURL,
				SERVICE_NAME);
		ComplaintProxyServicePortType port = ss.getComplaintProxyServiceSoap();

		String ServiceEndPointURL = PropertyUtil.constantFromProperties
				.getString("COMPLAINT_PROXY_SERVICE_ENDPOINT_URL");

		LOGGER.debug("End point URL from property file : "
				+ PropertyUtil.constantFromProperties
						.getString("COMPLAINT_PROXY_SERVICE_ENDPOINT_URL"));

		BindingProvider bindingProvider = (BindingProvider) port;
		bindingProvider.getRequestContext().put(
				BindingProvider.ENDPOINT_ADDRESS_PROPERTY, ServiceEndPointURL);

		LOGGER.debug("Exit getPort.");

		return port;
	}

	public com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormResponse insertRecsIntoCRMExtWebForm(
			com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormRequest 

_insertRecsIntoCRMExtWebForm_parameters)
			throws MalformedURLException {
		ComplaintProxyServicePortType port = getPort();
		com.mgi.complaintproxyservice.client.InsertRecsIntoCRMExtWebFormResponse _insertRecsIntoCRMExtWebForm__return 

= port
				.insertRecsIntoCRMExtWebForm(_insertRecsIntoCRMExtWebForm_parameters);
		return _insertRecsIntoCRMExtWebForm__return;
	}

}
