package com.paypal.adaptivepayment.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-01T15:56:41.244+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "AdaptivePayments", 
                  wsdlLocation = "AdaptivePayments.wsdl",
                  targetNamespace = "http://svcs.paypal.com/services") 
public class AdaptivePayments extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://svcs.paypal.com/services", "AdaptivePayments");
    public final static QName AdaptivePaymentsSOAP11Http = new QName("http://svcs.paypal.com/services", "AdaptivePaymentsSOAP11_http");
    static {
        URL url = AdaptivePayments.class.getResource("AdaptivePayments.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AdaptivePayments.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "AdaptivePayments.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public AdaptivePayments(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdaptivePayments(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdaptivePayments() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AdaptivePaymentsPortType
     */
    @WebEndpoint(name = "AdaptivePaymentsSOAP11_http")
    public AdaptivePaymentsPortType getAdaptivePaymentsSOAP11Http() {
        return super.getPort(AdaptivePaymentsSOAP11Http, AdaptivePaymentsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdaptivePaymentsPortType
     */
    @WebEndpoint(name = "AdaptivePaymentsSOAP11_http")
    public AdaptivePaymentsPortType getAdaptivePaymentsSOAP11Http(WebServiceFeature... features) {
        return super.getPort(AdaptivePaymentsSOAP11Http, AdaptivePaymentsPortType.class, features);
    }

}
