package com.paypal.adaptivepayment.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.MessageContext;

import org.apache.commons.configuration.PropertiesConfiguration;

import com.mgi.paypal.util.PropertyUtil;
import com.mgi.paypal.util.SOAPMessageLoggingHandler;
import com.mgi.paypal.util.StringOutputStream;

/**
 * This class was generated by Apache CXF 2.7.3 2013-03-01T15:56:40.901+05:30
 * Generated source version: 2.7.3
 * 
 */
public final class AdaptivePaymentsPortType_AdaptivePaymentsSOAP11Http_Client {
	public static OutputStream output = new StringOutputStream();

	public AdaptivePaymentsPortType_AdaptivePaymentsSOAP11Http_Client() {

	}

	PropertiesConfiguration constantFromProperties = new PropertyUtil()
			.getConstantPropertyConfig();

	public GetUserLimitsResponse getUserLimit(
			GetUserLimitsRequest getUserLimitsRequest)
			throws java.lang.Exception {
		AdaptivePaymentsPortType port = getPort();

		com.paypal.adaptivepayment.client.GetUserLimitsResponse _getUserLimits__return = null;
		try {
			_getUserLimits__return = port.getUserLimits(getUserLimitsRequest);

		} catch (PPFaultMessage objPpFaultMessage) {
			objPpFaultMessage.printStackTrace();
			FaultMessage objFaultMessage = objPpFaultMessage.getFaultInfo();
			ErrorData ed = objFaultMessage.getError().get(0);
			System.out
					.println("Expected exception: PPFaultMessage has occurred.");
			System.out.println("Error Code: " + ed.getErrorId()
					+ " FaultMessage" + ed.getMessage());
			System.out.println(objPpFaultMessage.toString());
		}

		return _getUserLimits__return;
	}

	public PayResponse getPay(PayRequest payRequest, String token)
			throws java.lang.Exception {
		AdaptivePaymentsPortType port = getPortForPay(token);

		com.paypal.adaptivepayment.client.PayResponse _PayResponse = null;
		try {
			_PayResponse = port.pay(payRequest);

		} catch (PPFaultMessage objPpFaultMessage) {
			objPpFaultMessage.printStackTrace();
			FaultMessage objFaultMessage = objPpFaultMessage.getFaultInfo();
			ErrorData ed = objFaultMessage.getError().get(0);
			System.out
					.println("Expected exception: PPFaultMessage has occurred.");
			System.out.println("Error Code: " + ed.getErrorId()
					+ " FaultMessage" + ed.getMessage());
			System.out.println(objPpFaultMessage.toString());
		}

		return _PayResponse;
	}

	private AdaptivePaymentsPortType getPortForPay(String token) {
		setCredentials();
		// String wsdlURL
		// ="https://svcs.sandbox.paypal.com/AdaptivePayments/Pay";
		String wsdlURL = constantFromProperties
				.getString("ADAPTIVE_PAYMENTS_PAY_URL");
		// "https://api.stage2cp07.stage.paypal.com/AdaptivePayments/Pay";

		AdaptivePayments ss = new AdaptivePayments();
		AdaptivePaymentsPortType port = ss.getAdaptivePaymentsSOAP11Http();
		BindingProvider bd = (BindingProvider) port;
		bd.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
				wsdlURL);
		// addLogHandler(bd);
		// setupHeaders(bd);
		setupHeadersForPay(bd, token);
		return port;
	}

	private AdaptivePaymentsPortType getPort() {
		// String wsdlURL =
		// "https://svcs.sandbox.paypal.com/AdaptivePayments/GetUserLimits";
		setCredentials();
		String wsdlURL = constantFromProperties
				.getString("ADAPTIVE_PAYMENTS_GET_USERLIMIT_URL");

		System.out.println("get User Limit URL : " + wsdlURL);
		
		AdaptivePayments ss = new AdaptivePayments();
		AdaptivePaymentsPortType port = ss.getAdaptivePaymentsSOAP11Http();
		BindingProvider bd = (BindingProvider) port;
		bd.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
				wsdlURL);
		addLogHandler(bd);
		setupHeaders(bd);
		return port;
	}

	private  void setCredentials() {
//		Security.setProperty("ssl.SocketFactory.provider",
//				"com.ibm.jsse2.SSLSocketFactoryImpl");
//		Security.setProperty("ssl.ServerSocketFactory.provider",
//				"com.ibm.jsse2.SSLServerSocketFactoryImpl");
		
		
//		Security.setProperty("ssl.SocketFactory.provider", "sun.security.ssl.SSLSocketFactoryImpl");
//		Security.setProperty("ssl.ServerSocketFactory.provider", "sun.security.ssl.SSLServerSocketFactoryImpl");

		System.setProperty("javax.net.ssl.trustStoreType",
				constantFromProperties.getString("trustStoreType"));
		System.setProperty("javax.net.ssl.trustStore",
				constantFromProperties.getString("trustStore"));
		System.setProperty("javax.net.ssl.trustStorePassword",
				constantFromProperties.getString("trustStorePassword"));
		System.setProperty("javax.net.ssl.keyStoreType",
				constantFromProperties.getString("keyStoreType"));
		System.setProperty("javax.net.ssl.keyStore",
				constantFromProperties.getString("keyStore"));
		System.setProperty("javax.net.ssl.keyStorePassword",
				constantFromProperties.getString("keyStorePassword"));

		// System.setProperty("javax.net.ssl.trustStoreType", "JKS");
		// System.setProperty("javax.net.ssl.trustStore",
		// "CXFRest/WebContent/WEB-INF/truststore.jks");
		// System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
		// System.setProperty("javax.net.ssl.keyStoreType", "pkcs12");
		// System.setProperty("javax.net.ssl.keyStore",
		// "CXFRest/WebContent/WEB-INF/paypal_cert.p12");
		// System.setProperty("javax.net.ssl.keyStorePassword", "changeit");

	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public static void addLogHandler(BindingProvider bp) {
		Binding binding = bp.getBinding();
		List handlerList = binding.getHandlerChain();
		if (handlerList == null)
			handlerList = new ArrayList();
		SOAPMessageLoggingHandler loggingHandler = new SOAPMessageLoggingHandler(
				output);
		handlerList.add(loggingHandler);
		binding.setHandlerChain(handlerList);

	}

	public  void setupHeaders(BindingProvider bp) {

		Map<String, List<String>> headers = new HashMap<String, List<String>>();
		// headers.put("X-PAYPAL-SECURITY-PASSWORD",
		// Collections.singletonList("1360057509"));
		// headers.put("X-PAYPAL-APPLICATION-ID",
		// Collections.singletonList("APP-80W284485P519543T"));
		headers.put("X-PAYPAL-SECURITY-PASSWORD",
				Collections.singletonList(constantFromProperties.getString("X_PAYPAL_SECURITY_PASSWORD")));

		headers.put("X-PAYPAL-APPLICATION-ID",
				Collections.singletonList(constantFromProperties.getString("X_PAYPAL_APPLICATION_ID")));
		headers.put("X-PAYPAL-SECURITY-USERID", Collections
				.singletonList(constantFromProperties.getString("X_PAYPAL_SECURITY_USERID")));
		
		System.out.println("Header Values");
		System.out.println("        ");
		System.out.println(headers.get("X-PAYPAL-SECURITY-PASSWORD"));
		System.out.println("        ");
		System.out.println(headers.get("X-PAYPAL-APPLICATION-ID"));
		System.out.println("        ");
		System.out.println(headers.get("X-PAYPAL-SECURITY-USERID"));

		// headers.put("X-PAYPAL-SECURITY-USERID", Collections
		// .singletonList("yathi_1360057489_biz_api1.gmail.com"));
		// headers.put(
		// "X-PAYPAL-SECURITY-SIGNATURE",
		// Collections
		// .singletonList("AnuN4vab8al1SfyKRXM4mSMYZQAmA8IvJIBGoIZVkt7XxF7W--tLgaXw"));
		bp.getRequestContext()
				.put(MessageContext.HTTP_REQUEST_HEADERS, headers);

	}

	public static void setupHeadersForPay(BindingProvider bp, String token) {

		/*
		 * System.out.println("Setting HTTP Header"); AccessToken accessToken =
		 * new AccessToken(); String Token = accessToken.getAccess_token();
		 */

		// String Tok="F2DcXe38dhK.Pxw1N.fhS9KJYed3lQAnPCnSCKYTj1Q";
		Map<String, List<String>> headers = new HashMap<String, List<String>>();
		headers.put("X-PAYPAL-SECURITY-PASSWORD",
				Collections.singletonList("SSARWLBQRLFMDLHH"));

		headers.put("X-PAYPAL-APPLICATION-ID",
				Collections.singletonList("APP-1JE4291016473214C"));
		headers.put("X-PAYPAL-SECURITY-USERID", Collections
				.singletonList("mgi_fundsout_test_api1.moneygram.com"));

		headers.put(
				"X-PAYPAL-SECONDARY-AUTH-UNIVERSAL-TOKEN ",
				Collections
						.singletonList(/* "Hia6.IbEOZ1kV-KvqETllw9vPBtrH-QoXu297bVRqy8" */token));
		bp.getRequestContext()
				.put(MessageContext.HTTP_REQUEST_HEADERS, headers);

	}
}
