package com.paypal.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-01T15:56:41.213+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://svcs.paypal.com/services", name = "AdaptivePaymentsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdaptivePaymentsPortType {

    @WebResult(name = "ConfirmPreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "ConfirmPreapproval", action = "urn:ConfirmPreapproval")
    public ConfirmPreapprovalResponse confirmPreapproval(
        @WebParam(partName = "body", name = "ConfirmPreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        ConfirmPreapprovalRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetAllowedFundingSourcesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetAllowedFundingSources", action = "urn:GetAllowedFundingSources")
    public GetAllowedFundingSourcesResponse getAllowedFundingSources(
        @WebParam(partName = "body", name = "GetAllowedFundingSourcesRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetAllowedFundingSourcesRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetUserLimitsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetUserLimits", action = "GetUserLimits")
    public GetUserLimitsResponse getUserLimits(
        @WebParam(partName = "body", name = "GetUserLimitsRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetUserLimitsRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetShippingAddressesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetShippingAddresses", action = "urn:GetShippingAddresses")
    public GetShippingAddressesResponse getShippingAddresses(
        @WebParam(partName = "body", name = "GetShippingAddressesRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetShippingAddressesRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "RefundResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "Refund", action = "urn:Refund")
    public RefundResponse refund(
        @WebParam(partName = "body", name = "RefundRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        RefundRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetAvailableShippingAddressesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetAvailableShippingAddresses", action = "urn:GetAvailableShippingAddresses")
    public GetAvailableShippingAddressesResponse getAvailableShippingAddresses(
        @WebParam(partName = "body", name = "GetAvailableShippingAddressesRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetAvailableShippingAddressesRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "SetPaymentOptionsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "SetPaymentOptions", action = "urn:SetPaymentOptions")
    public SetPaymentOptionsResponse setPaymentOptions(
        @WebParam(partName = "body", name = "SetPaymentOptionsRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        SetPaymentOptionsRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "ExecutePaymentResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "ExecutePayment", action = "urn:ExecutePayment")
    public ExecutePaymentResponse executePayment(
        @WebParam(partName = "body", name = "ExecutePaymentRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        ExecutePaymentRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetPaymentOptionsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetPaymentOptions", action = "urn:GetPaymentOptions")
    public GetPaymentOptionsResponse getPaymentOptions(
        @WebParam(partName = "body", name = "GetPaymentOptionsRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetPaymentOptionsRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "PaymentDetailsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "PaymentDetails", action = "urn:PaymentDetails")
    public PaymentDetailsResponse paymentDetails(
        @WebParam(partName = "body", name = "PaymentDetailsRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        PaymentDetailsRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "CancelPreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "CancelPreapproval", action = "urn:CancelPreapproval")
    public CancelPreapprovalResponse cancelPreapproval(
        @WebParam(partName = "body", name = "CancelPreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        CancelPreapprovalRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "PreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "Preapproval", action = "urn:Preapproval")
    public PreapprovalResponse preapproval(
        @WebParam(partName = "body", name = "PreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        PreapprovalRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "ConvertCurrencyResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "ConvertCurrency", action = "urn:ConvertCurrency")
    public ConvertCurrencyResponse convertCurrency(
        @WebParam(partName = "body", name = "ConvertCurrencyRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        ConvertCurrencyRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "PreapprovalDetailsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "PreapprovalDetails", action = "urn:PreapprovalDetails")
    public PreapprovalDetailsResponse preapprovalDetails(
        @WebParam(partName = "body", name = "PreapprovalDetailsRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        PreapprovalDetailsRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "GetFundingPlansResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "GetFundingPlans", action = "urn:GetFundingPlans")
    public GetFundingPlansResponse getFundingPlans(
        @WebParam(partName = "body", name = "GetFundingPlansRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        GetFundingPlansRequest body
    ) throws PPFaultMessage;

    @WebResult(name = "PayResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    @WebMethod(operationName = "Pay", action = "urn:Pay")
    public PayResponse pay(
        @WebParam(partName = "body", name = "PayRequest", targetNamespace = "http://svcs.paypal.com/types/ap")
        PayRequest body
    ) throws PPFaultMessage;
}
