package com.ac1211.mail.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-26T15:16:15.823+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "ComplaintProxyService_v1", 
                  wsdlLocation = "ComplaintProxyService_v1.wsdl",
                  targetNamespace = "http://moneygram.com/service/ComplaintProxyService_v1") 
public class ComplaintProxyServiceV1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://moneygram.com/service/ComplaintProxyService_v1", "ComplaintProxyService_v1");
    public final static QName ComplaintProxyServiceSoap = new QName("http://moneygram.com/service/ComplaintProxyService_v1", "ComplaintProxyServiceSoap");
    static {
        URL url = ComplaintProxyServiceV1.class.getResource("ComplaintProxyService_v1.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ComplaintProxyServiceV1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ComplaintProxyService_v1.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ComplaintProxyServiceV1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComplaintProxyServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComplaintProxyServiceV1() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ComplaintProxyServicePortType
     */
    @WebEndpoint(name = "ComplaintProxyServiceSoap")
    public ComplaintProxyServicePortType getComplaintProxyServiceSoap() {
        return super.getPort(ComplaintProxyServiceSoap, ComplaintProxyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComplaintProxyServicePortType
     */
    @WebEndpoint(name = "ComplaintProxyServiceSoap")
    public ComplaintProxyServicePortType getComplaintProxyServiceSoap(WebServiceFeature... features) {
        return super.getPort(ComplaintProxyServiceSoap, ComplaintProxyServicePortType.class, features);
    }

}
